- .gitignore
- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/models/user_viewing_party.rb
- app/models/viewing_party.rb
- db/migrate/20220822230909_create_users.rb
- db/migrate/20220822231709_create_viewing_parties.rb
- db/migrate/20220822231954_create_user_viewing_parties.rb
- db/schema.rb
- spec/models/user_spec.rb
- spec/models/user_viewing_party_spec.rb
- spec/models/viewing_party_spec.rb
Add migrations for all tables and create model tests
Added the migrations and created the model tests
> Create Migrations & Model Test

- Gemfile
- Gemfile.lock
- README.md
- app/models/user.rb
- app/models/viewing_party.rb
- config/application.rb
- spec/models/user_spec.rb
- spec/models/user_viewing_party_spec.rb
- spec/models/viewing_party_spec.rb
- spec/rails_helper.rb
Rubocop errors
Fixed errors that affected functionality. Limited corrections to working files and not those of which were automatically generated
Some double to single quotes where there is no interpolation
> rubocop corrections

- Gemfile
- Gemfile.lock
- README.md
- app/controllers/users_controller.rb
- app/models/user.rb
- app/models/viewing_party.rb
- app/views/users/show.html.erb
- config/application.rb
- config/routes.rb
- db/seeds.rb
- spec/features/users/show_spec.rb
- spec/models/user_spec.rb
- spec/models/user_viewing_party_spec.rb
- spec/models/viewing_party_spec.rb
- spec/rails_helper.rb
Set up user dashboard
Create Users controller and show page view
> Users merge 2nd

- Gemfile
- Gemfile.lock
- README.md
- app/controllers/landing_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/models/viewing_party.rb
- app/views/layouts/application.html.erb
- app/views/users/index.html.erb
- app/views/users/show.html.erb
- config/application.rb
- config/routes.rb
- db/seeds.rb
- spec/features/users/index_spec.rb
- spec/features/users/show_spec.rb
- spec/models/user_spec.rb
- spec/models/user_viewing_party_spec.rb
- spec/models/viewing_party_spec.rb
- spec/rails_helper.rb
Landing page list users as links to user dashboard
Removed landing controller and routed root page to users#index
> Landing merge 3rd

- Gemfile
- Gemfile.lock
- README.md
- app/controllers/landing_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/models/viewing_party.rb
- app/views/layouts/application.html.erb
- app/views/users/index.html.erb
- app/views/users/show.html.erb
- config/application.rb
- config/routes.rb
- db/seeds.rb
- spec/features/users/index_spec.rb
- spec/features/users/show_spec.rb
- spec/models/user_spec.rb
- spec/models/user_viewing_party_spec.rb
- spec/models/viewing_party_spec.rb
- spec/rails_helper.rb
User names as links to user dashboard
Tested for functionality of link
> User link merge 4th

- app/controllers/landing_controller.rb
- app/controllers/users_controller.rb
- app/views/layouts/application.html.erb
- app/views/users/index.html.erb
- app/views/users/new.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- spec/features/users/index_spec.rb
- spec/features/users/new_spec.rb
Register new user with redirect to new user's dashboard
In progress. Routing.
> New user merge last

- app/controllers/users_controller.rb
- config/routes.rb
- spec/features/users/new_spec.rb
Creating new user and routing to user dashboard
Added route and create in users controller. Will still need set up for password verification and uniqueness of email.
> New user created

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/new.html.erb
- spec/features/users/new_spec.rb
- spec/models/user_spec.rb
Validating uniqueness and case insensitivity of email (e.g. blakesaylor@gmail.com & Blakesaylor@gmail.com cannot both exist as email addresses in the table)
Added method within the User model to downcase email prior to saving and validations to check if the email is unique and case insensitive. 
Small changes to Register view -- Adding breaks and changing capitalization. Added flash message that displays if redirected due to non-unique email.
> Validating Email Uniqueness / View Refactoring

- app/assets/stylesheets/application.css
- app/views/users/index.html.erb
- app/views/users/new.html.erb
- app/views/users/show.html.erb
- spec/features/users/index_spec.rb
- spec/features/users/new_spec.rb
Updating views to resemble wireframes. Updating tests to use within blocks and be more robust
Added some div sections within views, update application stylesheet CSS, included within blocks in tests
> View Refactoring, Spec Refactoring

- Gemfile
- README.md
Heroku commands
Added to README moved gems to development, test
> Heroku commads

- .gitignore
- Gemfile
Run figaro for private files
bundle exec figaro install will need to resolve conflicts
> Figaro files

- README.md
- app/views/users/index.html.erb
- app/views/users/new.html.erb
- db/seeds.rb
- spec/features/users/discover_spec.rb
- spec/features/users/index_spec.rb
- spec/features/users/new_spec.rb
- spec/features/users/show_spec.rb
Change test users to username 
Changes placeholder in new user form and removed last names from test users and seed
> Edit test users

- app/views/users/index.html.erb
- app/views/users/new.html.erb
- spec/features/users/index_spec.rb
Emulate wireframe
Add Register a New User title
> Add title and refactor

- .gitignore
- app/facades/movie_facade.rb
- spec/features/movies/index_spec.rb
- spec/fixtures/vcr_cassettes/Movies_Index_Page/can_show_the_top_40_movies_from_the_API.yml
- spec/poros/movie_spec.rb
- spec/spec_helper.rb
Co-authored-by: Anna Marie Sterling <103849872+AMSterling@users.noreply.github.com>
Filter out certain folders that are not necessary to be tested. Fix testing for API call / discovery page.
Added filters in spec_helper, updated tests in discover_spec
> Further API Testing / Filtering Folders from Tests

- app/controllers/movies_controller.rb
- app/facades/movie_facade.rb
- app/poros/movie_details.rb
- app/services/movie_service.rb
- app/views/movies/index.html.erb
- app/views/movies/show.html.erb
Creating a show page with all details about a movie
Created service and facade to call the API to get movie details, reviews, and cast. Created poro movie_details that uses all data from API call.
Used poro within movie show page to display all data.
> Add movie show page, movie_details poro

- Gemfile.lock
- app/controllers/viewing_parties_controller.rb
- app/models/user.rb
- app/models/viewing_party.rb
- app/views/users/show.html.erb
- app/views/viewing_parties/new.html.erb
- db/migrate/20220822231709_create_viewing_parties.rb
- db/schema.rb
- spec/features/viewing_parties/new_spec.rb
- spec/fixtures/vcr_cassettes/Movies_Index_Page/can_show_the_top_40_movies_from_the_API.yml
- spec/fixtures/vcr_cassettes/Movies_Index_Page/can_show_the_top_40_movies_from_the_API_based_on_a_search_string.yml
- spec/fixtures/vcr_cassettes/Movies_Index_Page/has_a_link_to_the_show_page_for_movies.yml
- spec/fixtures/vcr_cassettes/Movies_Show_Page/has_a_button_to_create_a_viewing_party_for_the_movie.yml
- spec/fixtures/vcr_cassettes/Movies_Show_Page/shows_all_of_the_details_for_a_specific_movie.yml
- spec/fixtures/vcr_cassettes/New_Viewing_Party/displays_a_form_to_create_a_new_viewing_party.yml
- spec/models/viewing_party_spec.rb
Creating ViewingParties and UserViewingParties
Updates to new, create methods in ViewingParties controller
> Update to create viewing party and user viewing parties

- app/views/users/_party_info.html.erb
- app/views/users/show.html.erb
- app/views/viewing_parties/new.html.erb
- spec/features/users/show_spec.rb
- spec/fixtures/vcr_cassettes/the_User_show_page/displays_viewing_parties_which_the_user_is_invited.yml
- spec/fixtures/vcr_cassettes/the_User_show_page/has_a_section_that_displays_viewing_parties_hosted_by_the_user.yml
Viewing party info for host and antendee
Called on partial form from dashboard
> Viewing party partial form

- app/views/users/_party_info.html.erb
- app/views/viewing_parties/new.html.erb
- spec/features/users/new_spec.rb
- spec/features/users/show_spec.rb
- spec/features/viewing_parties/new_spec.rb
- spec/fixtures/vcr_cassettes/New_Viewing_Party/cannot_select_a_duration_shorter_than_runtime.yml
Add sad path and robustify tests
Tested that created user populates on user index. Date appears in correct format for viewing parties
> Robustify tests fix date

- app/models/user.rb
- spec/models/user_spec.rb
- spec/models/viewing_party_spec.rb
Fix absence of model tests
Added model tests
> Model Tests

- app/assets/stylesheets/application.css
- app/views/users/show.html.erb
- spec/features/viewing_parties/new_spec.rb
Display viewing parties inline
Add CSS and section/divs in view
> Display viewing parties inline

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/new.html.erb
- app/views/users/show.html.erb
- db/seeds.rb
- spec/features/movies/index_spec.rb
- spec/features/movies/show_spec.rb
- spec/features/users/discover_spec.rb
- spec/features/users/index_spec.rb
- spec/features/users/new_spec.rb
- spec/features/users/show_spec.rb
- spec/features/viewing_parties/new_spec.rb
- spec/models/user_spec.rb
Password confirmation and Date test not passing with extra space
Remove space between month and day from Date.tomorrow.strftime
Add password confirmation field to new user form and update test user subjects
Added spacing to test visit and expect lines
> Add password confirmation field

- app/controllers/users_controller.rb
- app/views/layouts/application.html.erb
- app/views/users/new.html.erb
- spec/features/users/new_spec.rb
Unique error messages for new user form
Used native @user.errors.full_messages.to_sentence
> Add new user validation error messages

- app/controllers/users_controller.rb
- app/views/layouts/application.html.erb
- app/views/users/index.html.erb
- app/views/users/login_form.html.erb
- config/routes.rb
- spec/features/users/login_spec.rb
User login
Add log in form with routes. Authenticate user exists from email params and authenticate password
> Add user login
